### ISSUE TITLE
Compilation into wasm fails for some patches

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/WebPd#143]
Got the error :

```
Whoops, the AssemblyScript compiler has crashed during optimize :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
▌     at t (file:///home/spiq/code/webpd/WebPd/bin/cli.mjs:885:4806)
▌     at r (file:///home/spiq/code/webpd/WebPd/bin/cli.mjs:888:5468)
▌     at wasm://wasm/0136228a:wasm-function[94]:0xed30
▌     at wasm://wasm/0136228a:wasm-function[1844]:0x192e2b
▌     at wasm://wasm/0136228a:wasm-function[4808]:0x2fa0aa
▌     at wasm://wasm/0136228a:wasm-function[730]:0xbf5b7
▌     at wasm://wasm/0136228a:wasm-function[4811]:0x2fb0c0
▌     at IC (file:///home/spiq/code/webpd/WebPd/bin/cli.mjs:888:160163)
▌     at wasm://wasm/0136228a:wasm-function[1366]:0x12679f
▌     at wasm://wasm/0136228a:wasm-function[7656]:0x40c120
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

this happens for example with the perc1 example from the website.

**Comment by sebpiq** [comment]
Release `1.0.0-alpha.7` should fix this for most patches. However it still fails with some files (see https://github.com/AssemblyScript/assemblyscript/issues/2810), but I cannot tell why.
